import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BellRing, CheckCircle2, DatabaseZap, FileLock2, GitBranch, LockKeyhole, Scale, TimerReset } from "lucide-react";
import { Button } from "@/components/ui/button";
import { MarketingLayout, PageIntro } from "@/components/claimsdesk/site-shell";
export const Route = createFileRoute("/features")({ head: () => ({ meta: [{ title: "Claims Workflow Features — ClaimsDesk" }, { name: "description", content: "Explore delegated authority, transactional integrity, SLA escalation, and audit controls in ClaimsDesk." }, { property: "og:title", content: "Claims Workflow Features — ClaimsDesk" }, { property: "og:description", content: "Enterprise controls for high-integrity insurance claims operations." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: FeaturesPage });
const items = [
  [GitBranch, "Delegated authority engine", "Encode insurer-specific approval bands by role, amount, line of business, and exception class.", ["Claims Officer: below KSh 100,000", "Underwriting Manager: below KSh 500,000", "Finance Director: KSh 500,000+"]],
  [DatabaseZap, "Financial transaction integrity", "Commit reserve releases, deductibles, and settlement entries as one atomic financial event.", ["Idempotent payout execution", "Policy balance locks", "Concurrent transaction safety"]],
  [BellRing, "Continuous SLA supervision", "Monitor every open claim around the clock and surface service risks before commitments are missed.", ["48-hour escalation rules", "Priority queue re-ranking", "Owner and supervisor alerts"]],
  [FileLock2, "Regulator-ready evidence", "Preserve who changed what, why it changed, and which authority approved every financial outcome.", ["Append-only decision history", "Timestamped evidence chain", "Exportable audit reports"]],
  [LockKeyhole, "Strict separation of duties", "Keep intake, assessment, authorization, payment, and audit permissions appropriately distinct.", ["Least-privilege access", "Role-specific work queues", "Read-only auditor mode"]],
  [TimerReset, "Operational resilience", "Keep work moving with safe retries, exception handling, and clear recovery states.", ["Retry-safe jobs", "Exception workbench", "Full event visibility"]],
] as const;
function FeaturesPage() { return <MarketingLayout><main><PageIntro eyebrow="Platform capabilities" title="Controls that make claims operations dependable." description="ClaimsDesk combines financial safeguards, configurable authority rules, and complete operational traceability in one focused platform." /><section className="py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map(([Icon,title,copy,bullets]) => <article key={title} className="feature-card"><span className="icon-well"><Icon /></span><h2 className="mt-7 text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p><ul className="mt-6 space-y-3 border-t border-border pt-5">{bullets.map(b => <li className="flex gap-2 text-xs font-medium" key={b}><CheckCircle2 className="size-4 shrink-0 text-brand" />{b}</li>)}</ul></article>)}</div></div></section><section className="bg-ink py-18 text-ink-foreground"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 px-5 md:flex-row md:items-center lg:px-8"><div><div className="flex items-center gap-2 text-brand-bright"><Scale className="size-5" /><span className="text-xs font-bold uppercase tracking-[.14em]">Designed for accountability</span></div><h2 className="mt-4 max-w-2xl text-3xl font-bold md:text-4xl">Operational speed without weakening financial governance.</h2></div><Button asChild variant="secondary"><Link to="/login">Try the staff portal <ArrowRight /></Link></Button></div></section></main></MarketingLayout>; }
